### ISSUE TITLE
NpgSqlexception Registration Service

### ISSUE THREAD

**Issue by hatoro** [bytefish/NancyOwinExample#1]
Hello, thank you for sharing.  I tried running the demo as outlined in your blog [post](http://bytefish.de/blog/token_authentication_owin_nancy/), but I am getting an exception error.  Error detail: {"28P01: password authentication failed for user \"philipp\""}

**Comment by hatoro** [comment]
I found a typo in the connection string in app.config. Change Id=philipp to Id=phillipp and it works!

**Comment by bytefish** [comment]
Great! This is a database configuration related issue, so I am closing the issue.
